# Generated by Django 2.0.2 on 2018-08-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20180824_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created'], 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AddField(
            model_name='service',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Completed'),
        ),
        migrations.AlterField(
            model_name='service',
            name='amount_donate',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='Amount donate'),
        ),
        migrations.AlterField(
            model_name='service',
            name='amount_needed',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='Amount needed'),
        ),
        migrations.AlterField(
            model_name='service',
            name='content',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of created'),
        ),
        migrations.AlterField(
            model_name='service',
            name='crw_donate',
            field=models.IntegerField(verbose_name='Crown needed'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='services', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='service',
            name='subtitle',
            field=models.CharField(max_length=200, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date of edition'),
        ),
        migrations.AlterField(
            model_name='service',
            name='wallet_donate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address for donate '),
        ),
        migrations.AlterField(
            model_name='service',
            name='wallet_self',
            field=models.CharField(max_length=100, verbose_name='Address User'),
        ),
        migrations.AlterField(
            model_name='service',
            name='wallet_shop',
            field=models.CharField(max_length=100, verbose_name='Address Shop'),
        ),
    ]
