# Generated by Django 2.0.2 on 2018-08-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20180828_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date of edition')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['-created'],
            },
        ),
        migrations.RemoveField(
            model_name='service',
            name='wallet_self',
        ),
        migrations.AddField(
            model_name='service',
            name='categories',
            field=models.ManyToManyField(related_name='get_services', to='services.Category', verbose_name='Categories'),
        ),
    ]
