# Generated by Django 2.0.2 on 2018-08-29 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20180829_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published'),
        ),
    ]
