# Generated by Django 2.0.2 on 2018-09-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20180830_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='progress',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Progress'),
        ),
    ]
